server:
  port: 8083

logging:
  level:
    org:
      springframework:
        data:
          r2dbc: DEBUG

spring:
  r2dbc:
    url: r2dbc:mysql//localhost:3306/wes?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: root
    password: fasstowes


